### ISSUE TITLE
生成after、before伪类时，不生效的问题

### ISSUE THREAD

**Issue by jiankun-wf** [07akioni/css-render#1101]
**运行环境**
1.   "css-render": "^0.15.12",
2.   "vite": "^4.1.0",
3.   "vue": "^3.2.45"
4.  node v16.13.0

**栗子**
  https://codesandbox.io/p/sandbox/elated-solomon-uqfc8e?file=%2Fsrc%2FApp.vue
**遇到的问题**
我需要生成一个div的after伪类
![code](https://user-images.githubusercontent.com/22322274/226257617-71499067-c631-49f3-9102-1d59dfaa4321.png)
![屏幕截图 2023-03-20 134436](https://user-images.githubusercontent.com/22322274/226256982-aa1c951e-72d0-4008-a099-9c0d82f60c1b.png)
但是生成的content 为空，然后就会导致这个伪类不生效

期待您的解答。

**Comment by 07akioni** [comment]
content 需要写成  '""'
