### ISSUE TITLE
Not all package.json files have license metadata

### ISSUE THREAD

**Issue by hyandell** [07akioni/css-render#293]
Hi 07akioni,

I noticed that not all of your package.json files have license metadata. Specifically, these ones seem to need an MIT license line:

https://github.com/07akioni/css-render/blob/master/packages/eslint-config/package.json
https://github.com/07akioni/css-render/blob/master/packages/test-shared/package.json
https://github.com/07akioni/css-render/blob/master/packages/vue3-ssr/package.json

**Comment by 07akioni** [comment]
> Hi 07akioni,
> 
> I noticed that not all of your package.json files have license metadata. Specifically, these ones seem to need an MIT license line:
> 
> https://github.com/07akioni/css-render/blob/master/packages/eslint-config/package.json
> https://github.com/07akioni/css-render/blob/master/packages/test-shared/package.json
> https://github.com/07akioni/css-render/blob/master/packages/vue3-ssr/package.json

Yes, they should be it licensed
